### PR TITLE
Don't generate a Vftbl nested type for non-generic interfaces (.NET 5 only)

### PR DESCRIPTION
**Pull request by jkoritzinsky**
To help reduce metadata size, this PR changes non-generic interfaces to not emit a Vftbl nested type and instead cast and dereference from `ThisPtr` directly and directly set entries on the `AbiToProjectionVtablePtr` vtable.

This reduces the Windows SDK projection from 28168 kb to 24340 kb (13% reduction) and reduces the WinUI projection from 12624 kb to 10713 kb (15% reduction).

In addition, since this PR adds first class support for types without Vftbl fields, it makes WinRT.Runtime a bit more resilient for linking.

It also reduces a bit of reflection in IWinRTObject and SingleInterfaceOptimizedObject.

Since this PR doesn't mandate when a Vftbl type is available, it is backward compatible with projections that generate Vftbl types on non-generic interfaces (and intermixing between ones that do and ones that don't).

### CODE REVIEW

**Comment by Scottj1s** [comment]
This is great, Jeremy - thx!  We'll want to build private cswinrt, Windows & WinUI projections to ensure no regressions before including in RTM.

**Comment by jkoritzinsky** [comment]
Awesome! Can you build the privates and share them out to the right people?

**Comment by jkoritzinsky** [comment]
cc: @AaronRobinsonMSFT

**Comment by Scottj1s** [comment]
> Awesome! Can you build the privates and share them out to the right people?

Yes, we're independently validating with Xaml Control Gallery, on private builds of cswinrt, Windows projection, WinUI projection

**Review by Scottj1s — APPROVED** [review]

**Comment by Scottj1s** [comment]
validation looks good!

**Pull request merged**
